#!/usr/bin/env bash
#
# Image-level smoke test for the chat-server Docker build.
# Sibling to scripts/smoke.sh (which exercises host-built binaries).
#
# Steps (issue #795):
#
#   1. docker compose up -d --build (using the repo's docker-compose.yml)
#   2. Wait for /healthz to return 200
#   3. Assert GET / returns the SPA HTML (catches //go:embed regressions)
#   4. Register + login a user via the HTTP API
#   5. Mint a ws-ticket, dial /ws via scripts/smoke-ws-helper, post a
#      message via POST /api/channels/{id}/messages, assert the helper
#      receives it
#   6. docker compose down -v (full cleanup)
#
# On any step failure: dump `docker compose logs` to $WORK_DIR/compose.log,
# print it, then teardown. Exits non-zero so CI fails fast.
#
# Concurrency: --project-name chat-smoke-$$ keeps two simultaneous runs
# (or a parallel scripts/smoke.sh) from colliding on container/volume names.
# We DO bind 8080 on the host (docker-compose.yml's `ports:` is unconditional);
# concurrent runs on the same host will fail at the second container start
# because of the port collision. CI runners run one job-per-runner, so this
# is fine for #795. A multi-run-on-one-host story is out of scope here.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PROJECT_NAME="chat-smoke-$$"
WORK_DIR="$(mktemp -d -t chat-smoke-docker.XXXXXX)"
ENV_FILE="$ROOT/.env"
ENV_BACKUP=""

API_HOST="127.0.0.1"
API_PORT="8080"
API_URL="http://${API_HOST}:${API_PORT}"

cleanup() {
  local rc=$?
  set +e

  if [[ $rc -ne 0 ]]; then
    echo "[smoke-docker] FAILED (rc=$rc); dumping compose logs" >&2
    docker compose --project-name "$PROJECT_NAME" logs --no-color \
      > "$WORK_DIR/compose.log" 2>&1
    echo "--- compose.log ---" >&2
    cat "$WORK_DIR/compose.log" >&2
  fi

  docker compose --project-name "$PROJECT_NAME" down -v --remove-orphans \
    >/dev/null 2>&1

  # Restore the operator's .env if we shadowed one.
  if [[ -n "$ENV_BACKUP" && -f "$ENV_BACKUP" ]]; then
    mv -f "$ENV_BACKUP" "$ENV_FILE"
  elif [[ -z "$ENV_BACKUP" && -f "$ENV_FILE.smoke-docker.marker" ]]; then
    # We created a fresh .env (no backup taken). Drop it on the way out.
    rm -f "$ENV_FILE" "$ENV_FILE.smoke-docker.marker"
  fi

  rm -rf "$WORK_DIR"
  exit $rc
}
trap cleanup EXIT INT TERM HUP

if ! command -v docker >/dev/null 2>&1; then
  echo "[smoke-docker] docker is required" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "[smoke-docker] 'docker compose' (V2) is required" >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "[smoke-docker] curl is required" >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "[smoke-docker] python3 is required (JSON envelope parsing)" >&2
  exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "[smoke-docker] openssl is required (per-run secret generation)" >&2
  exit 1
fi
if ! command -v go >/dev/null 2>&1; then
  echo "[smoke-docker] go is required (builds scripts/smoke-ws-helper)" >&2
  exit 1
fi

# ----- per-run secrets and .env --------------------------------------------
# CLAUDE.md "no hardcoded secrets": both values are generated per-run with
# openssl, never read from a committed file.
SMOKE_JWT_SECRET="$(openssl rand -hex 24)"   # 48 hex bytes, well over the 32-byte floor
SMOKE_INVITE_CODE="$(openssl rand -hex 8)"   # 16 hex bytes

if [[ -f "$ENV_FILE" ]]; then
  ENV_BACKUP="$WORK_DIR/.env.backup"
  cp -f "$ENV_FILE" "$ENV_BACKUP"
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/smoke-docker.sh — overwritten on every run.
# Original .env (if any) is restored in the cleanup trap.
CHAT_JWT_SECRET=${SMOKE_JWT_SECRET}
CHAT_INVITE_CODE=${SMOKE_INVITE_CODE}
CHAT_DB_PATH=/data/chat.db
CHAT_LISTEN_ADDR=0.0.0.0:${API_PORT}
CHAT_ALLOW_PUBLIC_BIND=1
EOF
# Marker so cleanup knows we created (vs. shadowed) this file.
[[ -z "$ENV_BACKUP" ]] && touch "$ENV_FILE.smoke-docker.marker"

# ----- build the WS helper -------------------------------------------------
# Built with the host toolchain (no CGO needed; coder/websocket is pure Go).
# Lives under $WORK_DIR so the repo tree stays clean.
WS_HELPER="$WORK_DIR/ws-helper"
echo "[smoke-docker] building scripts/smoke-ws-helper"
go build -o "$WS_HELPER" ./scripts/smoke-ws-helper

# ----- bring the stack up --------------------------------------------------
echo "[smoke-docker] docker compose up --build (project=$PROJECT_NAME)"
docker compose --project-name "$PROJECT_NAME" up -d --build

# ----- wait for /healthz ---------------------------------------------------
echo "[smoke-docker] waiting for ${API_URL}/healthz"
healthz_ready=0
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "${API_URL}/healthz" 2>/dev/null; then
    healthz_ready=1
    break
  fi
  sleep 1
done
if [[ $healthz_ready -ne 1 ]]; then
  echo "[smoke-docker] /healthz did not return 200 within 60s" >&2
  exit 1
fi

# ----- SPA HTML assertion (catches //go:embed regressions) -----------------
# apps/web/index.html: <div id="root"></div>. Vite preserves that node in
# the production build, so its absence from `GET /` means the embed.FS is
# missing the bundled SPA. Hard-fail with a clear message.
echo "[smoke-docker] asserting GET / contains the SPA root marker"
INDEX_HTML="$(curl -fsS "${API_URL}/")"
if ! printf '%s' "$INDEX_HTML" | grep -Fq '<div id="root">'; then
  echo "[smoke-docker] FAIL: GET / did not contain '<div id=\"root\">' — //go:embed regression?" >&2
  printf '%s\n' "$INDEX_HTML" | head -20 >&2
  exit 1
fi

# ----- register + login ----------------------------------------------------
SMOKE_USER="smoke-$$-$(date +%s)"
SMOKE_PASS="smoke-password-1234567890"

echo "[smoke-docker] register ${SMOKE_USER}"
REGISTER_RESP="$(curl -fsS -X POST "${API_URL}/api/auth/register" \
  -H 'Content-Type: application/json' \
  -d "{\"username\":\"${SMOKE_USER}\",\"password\":\"${SMOKE_PASS}\",\"invite_code\":\"${SMOKE_INVITE_CODE}\"}")"

# Register returns the JWT directly (status 201). No separate login round-trip
# is needed for the round-trip itself, but we still hit /api/auth/login below
# so the smoke covers both paths.
TOKEN="$(printf '%s' "$REGISTER_RESP" | python3 -c "
import json, sys
print(json.load(sys.stdin)['data']['token'])
")"
if [[ -z "$TOKEN" ]]; then
  echo "[smoke-docker] register did not yield a token: ${REGISTER_RESP}" >&2
  exit 1
fi

echo "[smoke-docker] login ${SMOKE_USER}"
LOGIN_RESP="$(curl -fsS -X POST "${API_URL}/api/auth/login" \
  -H 'Content-Type: application/json' \
  -d "{\"username\":\"${SMOKE_USER}\",\"password\":\"${SMOKE_PASS}\"}")"
TOKEN="$(printf '%s' "$LOGIN_RESP" | python3 -c "
import json, sys
print(json.load(sys.stdin)['data']['token'])
")"
if [[ -z "$TOKEN" ]]; then
  echo "[smoke-docker] login did not yield a token: ${LOGIN_RESP}" >&2
  exit 1
fi

# ----- find the seeded #general channel ------------------------------------
echo "[smoke-docker] resolving seeded #general channel id"
CHANNELS_RESP="$(curl -fsS "${API_URL}/api/channels" \
  -H "Authorization: Bearer ${TOKEN}")"
CHANNEL_ID="$(printf '%s' "$CHANNELS_RESP" | python3 -c "
import json, sys
env = json.load(sys.stdin)
for c in env['data']['channels']:
    if c['name'] == 'general':
        print(c['id'])
        break
")"
if [[ -z "$CHANNEL_ID" ]]; then
  echo "[smoke-docker] could not find seeded #general channel: ${CHANNELS_RESP}" >&2
  exit 1
fi

# ----- mint a ws-ticket ----------------------------------------------------
echo "[smoke-docker] minting ws-ticket"
TICKET_RESP="$(curl -fsS -X POST "${API_URL}/api/auth/ws-ticket" \
  -H "Authorization: Bearer ${TOKEN}")"
TICKET="$(printf '%s' "$TICKET_RESP" | python3 -c "
import json, sys
print(json.load(sys.stdin)['data']['ticket'])
")"
if [[ -z "$TICKET" ]]; then
  echo "[smoke-docker] ws-ticket mint failed: ${TICKET_RESP}" >&2
  exit 1
fi

# ----- start the WS helper -------------------------------------------------
MSG="smoke-docker-$$-$(date +%s%N)"
WS_URL="ws://${API_HOST}:${API_PORT}/ws?ticket=${TICKET}&channel=${CHANNEL_ID}"
WS_OUT="$WORK_DIR/ws-helper.out"
WS_ERR="$WORK_DIR/ws-helper.err"

echo "[smoke-docker] starting ws-helper (timeout 15s)"
"$WS_HELPER" -url "$WS_URL" -expect "$MSG" -timeout 15s \
  >"$WS_OUT" 2>"$WS_ERR" &
WS_PID=$!

# Brief grace period so the helper finishes the upgrade + presence frame
# before we publish. The hub fan-out is push-based, so the publish must
# happen *after* the subscriber is registered.
sleep 1

# ----- post a message -------------------------------------------------------
echo "[smoke-docker] posting message: ${MSG}"
POST_RESP="$(curl -fsS -X POST \
  "${API_URL}/api/channels/${CHANNEL_ID}/messages" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H 'Content-Type: application/json' \
  -d "{\"body\":\"${MSG}\"}")" || {
  echo "[smoke-docker] message POST failed" >&2
  kill "$WS_PID" 2>/dev/null
  wait "$WS_PID" 2>/dev/null
  exit 1
}

# ----- wait for the helper to confirm ---------------------------------------
if ! wait "$WS_PID"; then
  echo "[smoke-docker] FAIL: ws-helper did not observe ${MSG}" >&2
  echo "--- ws-helper.out ---" >&2
  cat "$WS_OUT" >&2
  echo "--- ws-helper.err ---" >&2
  cat "$WS_ERR" >&2
  echo "--- POST response ---" >&2
  printf '%s\n' "$POST_RESP" >&2
  exit 1
fi

echo "[smoke-docker] OK: ws-helper observed ${MSG}"
